baseURL = "http://demerly-architects.netlify.com"
languageCode = "en-us"
title = "Demerly Architects"
[outputs]
    page = ["HTML", "json"]
    section = ["HTML", "json"]
    home = ["HTML", "json"]
[taxonomies]