---
label: site-settings
hide_body: true
fields:
- type: field_group
  name: header
  label: Header Settings
  fields:
  - type: text
    name: brand
    label: Site title
    config:
      required: true
  - type: field_group
    name: logos
    label: Logos
    fields:
    - type: file
      name: mobile
      label: Mobile Logo
    - type: file
      name: desktop
      label: Desktop Logo
  - type: field_group
    name: linkLabels
    label: Link Labels
    fields:
    - type: text
      name: projects
      label: Projects
      config:
        required: true
    - type: text
      name: process
      label: Process
      config:
        required: true
    - type: text
      name: profile
      label: Profile
      config:
        required: true
    - type: text
      name: contact
      label: Contact
      config:
        required: true
- type: field_group
  name: footer
  label: Footer Settings
  fields:
  - type: text
    name: address
    label: Address
    config:
      required: true
  - type: text
    name: phone
    label: Phone
    config:
      required: true
  - type: text
    name: fax
    label: Fax
    config:
      required: true
