---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: _index.md
  label: Homepage
  match: "**/*"
- type: directory
  path: hugo/content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: hugo/content/contact
  label: Contact
  create: all
  match: "**/*"
- type: directory
  path: hugo/content/profile
  label: Profile
  create: all
  match: "**/*"
- type: directory
  path: hugo/content/projects
  label: Projects
  create: all
  match: "**/*"
- type: directory
  path: hugo/content/process
  label: Process
  create: all
  match: "**/*"
upload_dir: hugo/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.6
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.55.6
  preview_output_directory: public
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.55.6
